import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppProvider } from "~/contexts/app.context";
import "./globals.css";
import RootLayoutContainer from "./layout-container";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider>
          <RootLayoutContainer>
            <main>{children}</main>
          </RootLayoutContainer>
        </AppProvider>
      </body>
    </html>
  );
}
